[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Custom domain configuration
[context.production]
  command = "echo 'Deploying to fast.jovylle.com'"